POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Parhaat vinkit Pariisiin – matkaopas täydelliseen lomaan",
    "author": "Veera Bianca",
    "url": "https://veerabianca.com/parhaat-vinkit-pariisiin-matkaopas/",
    "likes": 2
}